#ifndef SQUARESIZES
#define SQUARESIZES

#define SQUARE_SIZE 10
#define SQUARE_RECT -SQUARE_SIZE/2,SQUARE_SIZE/2,SQUARE_SIZE,SQUARE_SIZE
#define CIRCLE_RADIUS 8
#define CIRCLE_RECT -CIRCLE_RADIUS/2,CIRCLE_RADIUS/2,CIRCLE_RADIUS,CIRCLE_RADIUS

#define LIGHT_SQUARE_COLOR 200,200,200
#define  DARK_SQUARE_COLOR 25,51,114

#endif // SQUARESIZES

