#ifndef SQUARESIZES
#define SQUARESIZES

#define SQUARE_SIZE 12*6
#define SQUARE_RECT -SQUARE_SIZE/2,-SQUARE_SIZE/2,SQUARE_SIZE,SQUARE_SIZE
#define CIRCLE_RADIUS 5*6
#define CIRCLE_RECT -CIRCLE_RADIUS,-CIRCLE_RADIUS,CIRCLE_RADIUS*2,CIRCLE_RADIUS*2

#define  DARK_SQUARE_COLOR 25,51,114

#define RED 0
#define BLK 1

#endif // SQUARESIZES

